### ISSUE TITLE
Internationnal standard for ice rinks

### ISSUE THREAD

**Issue by PierreVauclin** [andrewpucci/shotplot#15]
As an intern for a French ice hockey team, the dimensions of the ice rink make me make errors of judgment in the marking. Would it be possible to change the rink to a 6000cm by 3000cm rink? With the coodinate 0 for the center, xlim = -3000,3000 and ylim =-1500,1500. I added a link to an image but I could draw it myself if necessary. 

EDIT : 
I draw a rink with good dimension on python, I can save the file depending on the extension and the size you prefer. I have attached a png version.
![shot_plot](https://user-images.githubusercontent.com/43042918/54687288-82abad00-4b1b-11e9-9564-c425ed897f56.png)

Thank you.

**Comment by andrewpucci** [comment]
@PierreVauclin I intend to recreate a rink that I can use based on the measurements defined by the IIHF here: http://stats.iihf.com/hockey/rules/img/sec1.pdf

Let me know if that doesn't work for you.

**Comment by PierreVauclin** [comment]
@andrewpucci It's perfect.
